
name: CI

on:
  pull_request:
    branches:
      - main

env:
  VCS_ACCESS_TOKEN: ${{ secrets.VCS_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Set up Python 3.9 environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      # Run our smoke tests
      - name: Run smoke tests
        run: |
          pytest gus_dagster_project_tests
      
      # Run our unit tests
      - name: Run unit tests
        run: |
          dagster job execute -f gus_dagster_project/repository.py --job daily_refresh